ler = input('Digite alguma coisa: ')
print(f'O tipo primitivo desse texto é {type(ler)}')
print(f'Só tem espaço? {ler.isspace()}')
print(f'É um numero? {ler.isnumeric()}')
print(f'É alfabético? {ler.isalpha()}')
print(f'É alfanumérico? {ler.isalnum()}')
print(f'Está em maiusculo{ler.isupper()}')
print(f'Está em minusculo? {ler.islower()}')
print(f'Está capitalizado? {ler.istitle()}')
